from .image_repeat_node import NODE_CLASS_MAPPINGS as REPEAT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as REPEAT_DISPLAY_MAPPINGS
from .multi_image_compose import NODE_CLASS_MAPPINGS as COMPOSE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as COMPOSE_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**REPEAT_MAPPINGS, **COMPOSE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**REPEAT_DISPLAY_MAPPINGS, **COMPOSE_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
